/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uasgamef;

import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static uasgamef.koneksi.getConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INSTIKI
 */
public class form extends javax.swing.JFrame {
    DefaultTableModel tm = new DefaultTableModel();
    /**
     * Creates new form form
     * @throws java.sql.SQLException
     */
    public form() throws SQLException {
        initComponents();
        jtb.setModel(tm);
        tm.addColumn("ID Game");
        tm.addColumn("Nama Game");
        tm.addColumn("Developer");
        tm.addColumn("Asal Game");
        btndel.setEnabled(false);
        list_all();
    }
    
    private void list_all() throws SQLException{
        tm.getDataVector().removeAllElements();
        tm.fireTableDataChanged(); 
        Connection cnn = getConnection();
        if(cnn.isClosed()) {
            System.out.println("Koneksi Gagal");
        }else {
            String sql = "SELECT * FROM datagame order by id;";
            PreparedStatement ps=cnn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            while(rs.next()){
                Object[] dta = new Object[4];
                dta[0] = rs.getInt("id");
                dta[1] = rs.getString("nama_game");
                dta[2] = rs.getString("developer");
                dta[3] = rs.getString("asal");
                tm.addRow(dta);
            }
            cnn.close();
        }
    }

    private void Storedata() throws SQLException{
        Connection cnn = getConnection();
        String NM = formnama.getText();
        String DV = formdeveloper.getText();
        String AL = formasal.getText();
        
        if(!cnn.isClosed()) {
           PreparedStatement ps = cnn.prepareStatement("INSERT INTO datagame(nama_game,developer,asal)VALUES(?,?,?)");
           ps.setString(1, NM);
           ps.setString(2, DV);
           ps.setString(3, AL);
           ps.executeUpdate();
        }
    }
    
    private void dataupdate() throws SQLException{
        Connection cnn = getConnection();
        if(!cnn.isClosed()){
            String id = labelid.getText();
            String NM = formnama.getText();
            String DV = formdeveloper.getText();
            String AL = formasal.getText();
            PreparedStatement ps = cnn.prepareStatement("UPDATE datagame SET nama_game=?, developer=?, asal=? WHERE id=?");
            ps.setString(1, NM);
            ps.setString(2, DV);
            ps.setString(3, AL);
            ps.setString(4, id);
            ps.executeUpdate();
            
            cnn.close();
        }
    
    }
    
    private void DestroyData() throws SQLException {
    Connection cnn = getConnection();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("DELETE FROM datagame WHERE id = ?");
        ps.setString(1, labelid.getText());
        ps.executeUpdate();
        // Reset auto-increment setelah menghapus data
        PreparedStatement resetPs = cnn.prepareStatement("ALTER TABLE datagame AUTO_INCREMENT = 1");
        resetPs.executeUpdate();
        cnn.close();
    }
}
    
    
    private void loadfoto(String id){
        String pas0 = "img/foto.png";
        String pas = "img/foto"+id+".png";
        
        BufferedImage bimg = loadimg.loadimage(pas);
        if(bimg==null){
            bimg = loadimg.loadimage(pas0);
        }
        ImageIcon icoimg = new ImageIcon(bimg);
        pasfoto.setIcon(icoimg);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        formnama = new javax.swing.JTextField();
        formdeveloper = new javax.swing.JTextField();
        formasal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btntutup = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        labelid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pasfoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb);

        jLabel1.setFont(new java.awt.Font("Stylus BT", 1, 24)); // NOI18N
        jLabel1.setText("Data Game");

        formnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnamaActionPerformed(evt);
            }
        });

        formasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formasalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Nama Game:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Developer");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Asal Game");

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btntutup.setText("Close");
        btntutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntutupActionPerformed(evt);
            }
        });

        btndel.setText("Hapus");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        labelid.setText("-");

        jLabel5.setText("ID Game: ");

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        pasfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto.png"))); // NOI18N
        pasfoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(formasal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(formdeveloper)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnedit)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnadd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addComponent(btntutup)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(labelid))))
                                .addGap(18, 18, 18)
                                .addComponent(pasfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelid)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(formnama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formdeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(formasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndel)
                            .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntutup)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pasfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnamaActionPerformed

    private void formasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formasalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formasalActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
    if(btnadd.getText().equals("Add")){
        btnadd.setText("Save");
        btntutup.setText("Batal");
        btndel.setEnabled(false);
        
        labelid.setText("");
        formnama.setText("");
        formdeveloper.setText("");
        formasal.setText("");
    }
    else{
        try {
            Storedata();
            list_all();
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnadd.setText("Add");
        btntutup.setText("Close");
        btndel.setEnabled(true);
    }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
       
        
        try {
            
            int jtp = JOptionPane.showOptionDialog(this, "Yakin Mau Hapus Nama Game : "+formnama.getText()+"?", "Konfirmasi Tutup Form", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
            if(jtp == JOptionPane.YES_OPTION)
            DestroyData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          list_all();
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btndelActionPerformed

    private void jtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMouseClicked
         if (jtb.getSelectedRow() != -1) { // Periksa apakah ada data yang dipilih
        labelid.setText(jtb.getValueAt(jtb.getSelectedRow(), 0).toString());
        formnama.setText(jtb.getValueAt(jtb.getSelectedRow(), 1).toString());
        formdeveloper.setText(jtb.getValueAt(jtb.getSelectedRow(), 2).toString());
        formasal.setText(jtb.getValueAt(jtb.getSelectedRow(), 3).toString());
        loadfoto(labelid.getText());
        
        
        btndel.setEnabled(true); // Aktifkan tombol hapus setelah memilih data
    } else {
        btndel.setEnabled(false); // Nonaktifkan tombol hapus jika tidak ada data yang dipilih
    }

    }//GEN-LAST:event_jtbMouseClicked

    private void btntutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntutupActionPerformed
        
        if(btntutup.getText().equals("Close")){
            int tutupski=JOptionPane.showOptionDialog(this, "Yakin menutup form?", "Konfirmasi Tutup Form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(tutupski==JOptionPane.YES_NO_OPTION){
                dispose();
            }
                
            
        }
        else{
           btntutup.setText("Close");
           btnadd.setText("Add");
          btndel.setEnabled(true);
        }
        
    }//GEN-LAST:event_btntutupActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        try {
            dataupdate();
            list_all();
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new form().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btntutup;
    private javax.swing.JTextField formasal;
    private javax.swing.JTextField formdeveloper;
    private javax.swing.JTextField formnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel pasfoto;
    // End of variables declaration//GEN-END:variables
}
